// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.0
// source: cluster.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LoginService_Authenticate_FullMethodName = "/gs.cluster.LoginService/Authenticate"
	LoginService_Register_FullMethodName     = "/gs.cluster.LoginService/Register"
)

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginServiceClient interface {
	// 登录：账号不存在返回 ok=false, reason="账号不存在"（需先注册）
	Authenticate(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthRsp, error)
	// 注册：账号已存在返回 ok=false, reason="账号已存在"；成功后直接签发 token（自动登录）
	Register(ctx context.Context, in *RegisterAccountReq, opts ...grpc.CallOption) (*RegisterAccountRsp, error)
}

type loginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginServiceClient(cc grpc.ClientConnInterface) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) Authenticate(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthRsp, error) {
	out := new(AuthRsp)
	err := c.cc.Invoke(ctx, LoginService_Authenticate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) Register(ctx context.Context, in *RegisterAccountReq, opts ...grpc.CallOption) (*RegisterAccountRsp, error) {
	out := new(RegisterAccountRsp)
	err := c.cc.Invoke(ctx, LoginService_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the server API for LoginService service.
// All implementations must embed UnimplementedLoginServiceServer
// for forward compatibility
type LoginServiceServer interface {
	// 登录：账号不存在返回 ok=false, reason="账号不存在"（需先注册）
	Authenticate(context.Context, *AuthReq) (*AuthRsp, error)
	// 注册：账号已存在返回 ok=false, reason="账号已存在"；成功后直接签发 token（自动登录）
	Register(context.Context, *RegisterAccountReq) (*RegisterAccountRsp, error)
	mustEmbedUnimplementedLoginServiceServer()
}

// UnimplementedLoginServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLoginServiceServer struct {
}

func (UnimplementedLoginServiceServer) Authenticate(context.Context, *AuthReq) (*AuthRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedLoginServiceServer) Register(context.Context, *RegisterAccountReq) (*RegisterAccountRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedLoginServiceServer) mustEmbedUnimplementedLoginServiceServer() {}

// UnsafeLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginServiceServer will
// result in compilation errors.
type UnsafeLoginServiceServer interface {
	mustEmbedUnimplementedLoginServiceServer()
}

func RegisterLoginServiceServer(s grpc.ServiceRegistrar, srv LoginServiceServer) {
	s.RegisterService(&LoginService_ServiceDesc, srv)
}

func _LoginService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).Authenticate(ctx, req.(*AuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).Register(ctx, req.(*RegisterAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginService_ServiceDesc is the grpc.ServiceDesc for LoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gs.cluster.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _LoginService_Authenticate_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _LoginService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}

const (
	CenterService_VerifyToken_FullMethodName     = "/gs.cluster.CenterService/VerifyToken"
	CenterService_RegisterService_FullMethodName = "/gs.cluster.CenterService/RegisterService"
	CenterService_GetServiceList_FullMethodName  = "/gs.cluster.CenterService/GetServiceList"
	CenterService_Heartbeat_FullMethodName       = "/gs.cluster.CenterService/Heartbeat"
)

// CenterServiceClient is the client API for CenterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CenterServiceClient interface {
	// 校验 token，返回玩家信息（网关登录后调用）
	VerifyToken(ctx context.Context, in *TokenReq, opts ...grpc.CallOption) (*TokenRsp, error)
	// 服务注册（各微服务启动时调用）
	RegisterService(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegRsp, error)
	// 获取服务列表（服务发现）
	GetServiceList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceList, error)
	// 服务心跳保活
	Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*Empty, error)
}

type centerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCenterServiceClient(cc grpc.ClientConnInterface) CenterServiceClient {
	return &centerServiceClient{cc}
}

func (c *centerServiceClient) VerifyToken(ctx context.Context, in *TokenReq, opts ...grpc.CallOption) (*TokenRsp, error) {
	out := new(TokenRsp)
	err := c.cc.Invoke(ctx, CenterService_VerifyToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerServiceClient) RegisterService(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegRsp, error) {
	out := new(RegRsp)
	err := c.cc.Invoke(ctx, CenterService_RegisterService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerServiceClient) GetServiceList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceList, error) {
	out := new(ServiceList)
	err := c.cc.Invoke(ctx, CenterService_GetServiceList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, CenterService_Heartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CenterServiceServer is the server API for CenterService service.
// All implementations must embed UnimplementedCenterServiceServer
// for forward compatibility
type CenterServiceServer interface {
	// 校验 token，返回玩家信息（网关登录后调用）
	VerifyToken(context.Context, *TokenReq) (*TokenRsp, error)
	// 服务注册（各微服务启动时调用）
	RegisterService(context.Context, *RegReq) (*RegRsp, error)
	// 获取服务列表（服务发现）
	GetServiceList(context.Context, *Empty) (*ServiceList, error)
	// 服务心跳保活
	Heartbeat(context.Context, *HeartbeatReq) (*Empty, error)
	mustEmbedUnimplementedCenterServiceServer()
}

// UnimplementedCenterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCenterServiceServer struct {
}

func (UnimplementedCenterServiceServer) VerifyToken(context.Context, *TokenReq) (*TokenRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedCenterServiceServer) RegisterService(context.Context, *RegReq) (*RegRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterService not implemented")
}
func (UnimplementedCenterServiceServer) GetServiceList(context.Context, *Empty) (*ServiceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceList not implemented")
}
func (UnimplementedCenterServiceServer) Heartbeat(context.Context, *HeartbeatReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCenterServiceServer) mustEmbedUnimplementedCenterServiceServer() {}

// UnsafeCenterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CenterServiceServer will
// result in compilation errors.
type UnsafeCenterServiceServer interface {
	mustEmbedUnimplementedCenterServiceServer()
}

func RegisterCenterServiceServer(s grpc.ServiceRegistrar, srv CenterServiceServer) {
	s.RegisterService(&CenterService_ServiceDesc, srv)
}

func _CenterService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterService_VerifyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterServiceServer).VerifyToken(ctx, req.(*TokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterService_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterServiceServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterService_RegisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterServiceServer).RegisterService(ctx, req.(*RegReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterService_GetServiceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterServiceServer).GetServiceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterService_GetServiceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterServiceServer).GetServiceList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterServiceServer).Heartbeat(ctx, req.(*HeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CenterService_ServiceDesc is the grpc.ServiceDesc for CenterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CenterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gs.cluster.CenterService",
	HandlerType: (*CenterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _CenterService_VerifyToken_Handler,
		},
		{
			MethodName: "RegisterService",
			Handler:    _CenterService_RegisterService_Handler,
		},
		{
			MethodName: "GetServiceList",
			Handler:    _CenterService_GetServiceList_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CenterService_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}

const (
	BattleService_CreateBattle_FullMethodName = "/gs.cluster.BattleService/CreateBattle"
	BattleService_SubmitOp_FullMethodName     = "/gs.cluster.BattleService/SubmitOp"
	BattleService_FinishBattle_FullMethodName = "/gs.cluster.BattleService/FinishBattle"
)

// BattleServiceClient is the client API for BattleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BattleServiceClient interface {
	CreateBattle(ctx context.Context, in *CreateBattleReq, opts ...grpc.CallOption) (*CreateBattleRsp, error)
	SubmitOp(ctx context.Context, in *SubmitOpReq, opts ...grpc.CallOption) (*SubmitOpRsp, error)
	FinishBattle(ctx context.Context, in *FinishReq, opts ...grpc.CallOption) (*Empty, error)
}

type battleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBattleServiceClient(cc grpc.ClientConnInterface) BattleServiceClient {
	return &battleServiceClient{cc}
}

func (c *battleServiceClient) CreateBattle(ctx context.Context, in *CreateBattleReq, opts ...grpc.CallOption) (*CreateBattleRsp, error) {
	out := new(CreateBattleRsp)
	err := c.cc.Invoke(ctx, BattleService_CreateBattle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) SubmitOp(ctx context.Context, in *SubmitOpReq, opts ...grpc.CallOption) (*SubmitOpRsp, error) {
	out := new(SubmitOpRsp)
	err := c.cc.Invoke(ctx, BattleService_SubmitOp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) FinishBattle(ctx context.Context, in *FinishReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, BattleService_FinishBattle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BattleServiceServer is the server API for BattleService service.
// All implementations must embed UnimplementedBattleServiceServer
// for forward compatibility
type BattleServiceServer interface {
	CreateBattle(context.Context, *CreateBattleReq) (*CreateBattleRsp, error)
	SubmitOp(context.Context, *SubmitOpReq) (*SubmitOpRsp, error)
	FinishBattle(context.Context, *FinishReq) (*Empty, error)
	mustEmbedUnimplementedBattleServiceServer()
}

// UnimplementedBattleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBattleServiceServer struct {
}

func (UnimplementedBattleServiceServer) CreateBattle(context.Context, *CreateBattleReq) (*CreateBattleRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBattle not implemented")
}
func (UnimplementedBattleServiceServer) SubmitOp(context.Context, *SubmitOpReq) (*SubmitOpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOp not implemented")
}
func (UnimplementedBattleServiceServer) FinishBattle(context.Context, *FinishReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishBattle not implemented")
}
func (UnimplementedBattleServiceServer) mustEmbedUnimplementedBattleServiceServer() {}

// UnsafeBattleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BattleServiceServer will
// result in compilation errors.
type UnsafeBattleServiceServer interface {
	mustEmbedUnimplementedBattleServiceServer()
}

func RegisterBattleServiceServer(s grpc.ServiceRegistrar, srv BattleServiceServer) {
	s.RegisterService(&BattleService_ServiceDesc, srv)
}

func _BattleService_CreateBattle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBattleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).CreateBattle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_CreateBattle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).CreateBattle(ctx, req.(*CreateBattleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_SubmitOp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitOpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).SubmitOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_SubmitOp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).SubmitOp(ctx, req.(*SubmitOpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_FinishBattle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).FinishBattle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_FinishBattle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).FinishBattle(ctx, req.(*FinishReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BattleService_ServiceDesc is the grpc.ServiceDesc for BattleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BattleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gs.cluster.BattleService",
	HandlerType: (*BattleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBattle",
			Handler:    _BattleService_CreateBattle_Handler,
		},
		{
			MethodName: "SubmitOp",
			Handler:    _BattleService_SubmitOp_Handler,
		},
		{
			MethodName: "FinishBattle",
			Handler:    _BattleService_FinishBattle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}

const (
	GameService_JoinMatch_FullMethodName        = "/gs.cluster.GameService/JoinMatch"
	GameService_QueryMatchResult_FullMethodName = "/gs.cluster.GameService/QueryMatchResult"
	GameService_SubmitOp_FullMethodName         = "/gs.cluster.GameService/SubmitOp"
	GameService_QuitRoom_FullMethodName         = "/gs.cluster.GameService/QuitRoom"
	GameService_LeaveMatch_FullMethodName       = "/gs.cluster.GameService/LeaveMatch"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	// 玩家匹配进房（2 人凑齐即开局）。匹配不阻塞：入队后立即返回
	// room_id=0 表示排队中，网关轮询 QueryMatchResult 获取配对结果。
	JoinMatch(ctx context.Context, in *MatchJoinReq, opts ...grpc.CallOption) (*MatchJoinRsp, error)
	// 查询匹配结果（网关轮询，room_id=0 表示仍在排队）
	QueryMatchResult(ctx context.Context, in *MatchQueryReq, opts ...grpc.CallOption) (*MatchQueryRsp, error)
	// 转发玩家操作给房间
	SubmitOp(ctx context.Context, in *OpForwardReq, opts ...grpc.CallOption) (*OpForwardRsp, error)
	// 玩家主动退出房间
	QuitRoom(ctx context.Context, in *QuitRoomReq, opts ...grpc.CallOption) (*Empty, error)
	// 玩家在匹配等待中下线：从匹配池移除，避免配到死连接（广播给所有 game 实例，幂等）
	LeaveMatch(ctx context.Context, in *LeaveMatchReq, opts ...grpc.CallOption) (*Empty, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) JoinMatch(ctx context.Context, in *MatchJoinReq, opts ...grpc.CallOption) (*MatchJoinRsp, error) {
	out := new(MatchJoinRsp)
	err := c.cc.Invoke(ctx, GameService_JoinMatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) QueryMatchResult(ctx context.Context, in *MatchQueryReq, opts ...grpc.CallOption) (*MatchQueryRsp, error) {
	out := new(MatchQueryRsp)
	err := c.cc.Invoke(ctx, GameService_QueryMatchResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) SubmitOp(ctx context.Context, in *OpForwardReq, opts ...grpc.CallOption) (*OpForwardRsp, error) {
	out := new(OpForwardRsp)
	err := c.cc.Invoke(ctx, GameService_SubmitOp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) QuitRoom(ctx context.Context, in *QuitRoomReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, GameService_QuitRoom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) LeaveMatch(ctx context.Context, in *LeaveMatchReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, GameService_LeaveMatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility
type GameServiceServer interface {
	// 玩家匹配进房（2 人凑齐即开局）。匹配不阻塞：入队后立即返回
	// room_id=0 表示排队中，网关轮询 QueryMatchResult 获取配对结果。
	JoinMatch(context.Context, *MatchJoinReq) (*MatchJoinRsp, error)
	// 查询匹配结果（网关轮询，room_id=0 表示仍在排队）
	QueryMatchResult(context.Context, *MatchQueryReq) (*MatchQueryRsp, error)
	// 转发玩家操作给房间
	SubmitOp(context.Context, *OpForwardReq) (*OpForwardRsp, error)
	// 玩家主动退出房间
	QuitRoom(context.Context, *QuitRoomReq) (*Empty, error)
	// 玩家在匹配等待中下线：从匹配池移除，避免配到死连接（广播给所有 game 实例，幂等）
	LeaveMatch(context.Context, *LeaveMatchReq) (*Empty, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (UnimplementedGameServiceServer) JoinMatch(context.Context, *MatchJoinReq) (*MatchJoinRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinMatch not implemented")
}
func (UnimplementedGameServiceServer) QueryMatchResult(context.Context, *MatchQueryReq) (*MatchQueryRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMatchResult not implemented")
}
func (UnimplementedGameServiceServer) SubmitOp(context.Context, *OpForwardReq) (*OpForwardRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOp not implemented")
}
func (UnimplementedGameServiceServer) QuitRoom(context.Context, *QuitRoomReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuitRoom not implemented")
}
func (UnimplementedGameServiceServer) LeaveMatch(context.Context, *LeaveMatchReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveMatch not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_JoinMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchJoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).JoinMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_JoinMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).JoinMatch(ctx, req.(*MatchJoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_QueryMatchResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).QueryMatchResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_QueryMatchResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).QueryMatchResult(ctx, req.(*MatchQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_SubmitOp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpForwardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).SubmitOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_SubmitOp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).SubmitOp(ctx, req.(*OpForwardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_QuitRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).QuitRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_QuitRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).QuitRoom(ctx, req.(*QuitRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_LeaveMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveMatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).LeaveMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_LeaveMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).LeaveMatch(ctx, req.(*LeaveMatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gs.cluster.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinMatch",
			Handler:    _GameService_JoinMatch_Handler,
		},
		{
			MethodName: "QueryMatchResult",
			Handler:    _GameService_QueryMatchResult_Handler,
		},
		{
			MethodName: "SubmitOp",
			Handler:    _GameService_SubmitOp_Handler,
		},
		{
			MethodName: "QuitRoom",
			Handler:    _GameService_QuitRoom_Handler,
		},
		{
			MethodName: "LeaveMatch",
			Handler:    _GameService_LeaveMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}

const (
	GatewayPushService_PushSnapshot_FullMethodName = "/gs.cluster.GatewayPushService/PushSnapshot"
	GatewayPushService_PushFrame_FullMethodName    = "/gs.cluster.GatewayPushService/PushFrame"
	GatewayPushService_PushResult_FullMethodName   = "/gs.cluster.GatewayPushService/PushResult"
)

// GatewayPushServiceClient is the client API for GatewayPushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayPushServiceClient interface {
	// 游戏服把状态快照推给网关，由网关转给玩家（状态同步模式）
	PushSnapshot(ctx context.Context, in *SnapshotPushReq, opts ...grpc.CallOption) (*Empty, error)
	// 游戏服把输入帧推给网关，由网关转给玩家（帧同步模式）
	PushFrame(ctx context.Context, in *FramePushReq, opts ...grpc.CallOption) (*Empty, error)
	// 对局结束推送结果
	PushResult(ctx context.Context, in *ResultPushReq, opts ...grpc.CallOption) (*Empty, error)
}

type gatewayPushServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayPushServiceClient(cc grpc.ClientConnInterface) GatewayPushServiceClient {
	return &gatewayPushServiceClient{cc}
}

func (c *gatewayPushServiceClient) PushSnapshot(ctx context.Context, in *SnapshotPushReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, GatewayPushService_PushSnapshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayPushServiceClient) PushFrame(ctx context.Context, in *FramePushReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, GatewayPushService_PushFrame_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayPushServiceClient) PushResult(ctx context.Context, in *ResultPushReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, GatewayPushService_PushResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayPushServiceServer is the server API for GatewayPushService service.
// All implementations must embed UnimplementedGatewayPushServiceServer
// for forward compatibility
type GatewayPushServiceServer interface {
	// 游戏服把状态快照推给网关，由网关转给玩家（状态同步模式）
	PushSnapshot(context.Context, *SnapshotPushReq) (*Empty, error)
	// 游戏服把输入帧推给网关，由网关转给玩家（帧同步模式）
	PushFrame(context.Context, *FramePushReq) (*Empty, error)
	// 对局结束推送结果
	PushResult(context.Context, *ResultPushReq) (*Empty, error)
	mustEmbedUnimplementedGatewayPushServiceServer()
}

// UnimplementedGatewayPushServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayPushServiceServer struct {
}

func (UnimplementedGatewayPushServiceServer) PushSnapshot(context.Context, *SnapshotPushReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushSnapshot not implemented")
}
func (UnimplementedGatewayPushServiceServer) PushFrame(context.Context, *FramePushReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushFrame not implemented")
}
func (UnimplementedGatewayPushServiceServer) PushResult(context.Context, *ResultPushReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushResult not implemented")
}
func (UnimplementedGatewayPushServiceServer) mustEmbedUnimplementedGatewayPushServiceServer() {}

// UnsafeGatewayPushServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayPushServiceServer will
// result in compilation errors.
type UnsafeGatewayPushServiceServer interface {
	mustEmbedUnimplementedGatewayPushServiceServer()
}

func RegisterGatewayPushServiceServer(s grpc.ServiceRegistrar, srv GatewayPushServiceServer) {
	s.RegisterService(&GatewayPushService_ServiceDesc, srv)
}

func _GatewayPushService_PushSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotPushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayPushServiceServer).PushSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayPushService_PushSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayPushServiceServer).PushSnapshot(ctx, req.(*SnapshotPushReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayPushService_PushFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FramePushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayPushServiceServer).PushFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayPushService_PushFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayPushServiceServer).PushFrame(ctx, req.(*FramePushReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayPushService_PushResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultPushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayPushServiceServer).PushResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayPushService_PushResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayPushServiceServer).PushResult(ctx, req.(*ResultPushReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayPushService_ServiceDesc is the grpc.ServiceDesc for GatewayPushService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayPushService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gs.cluster.GatewayPushService",
	HandlerType: (*GatewayPushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushSnapshot",
			Handler:    _GatewayPushService_PushSnapshot_Handler,
		},
		{
			MethodName: "PushFrame",
			Handler:    _GatewayPushService_PushFrame_Handler,
		},
		{
			MethodName: "PushResult",
			Handler:    _GatewayPushService_PushResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}

const (
	RankService_SubmitScore_FullMethodName = "/gs.cluster.RankService/SubmitScore"
	RankService_GetTopN_FullMethodName     = "/gs.cluster.RankService/GetTopN"
)

// RankServiceClient is the client API for RankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RankServiceClient interface {
	// 提交一场战斗的分数
	SubmitScore(ctx context.Context, in *ScoreReq, opts ...grpc.CallOption) (*ScoreRsp, error)
	// 获取 TopN 排行
	GetTopN(ctx context.Context, in *TopNReq, opts ...grpc.CallOption) (*TopNRsp, error)
}

type rankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRankServiceClient(cc grpc.ClientConnInterface) RankServiceClient {
	return &rankServiceClient{cc}
}

func (c *rankServiceClient) SubmitScore(ctx context.Context, in *ScoreReq, opts ...grpc.CallOption) (*ScoreRsp, error) {
	out := new(ScoreRsp)
	err := c.cc.Invoke(ctx, RankService_SubmitScore_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankServiceClient) GetTopN(ctx context.Context, in *TopNReq, opts ...grpc.CallOption) (*TopNRsp, error) {
	out := new(TopNRsp)
	err := c.cc.Invoke(ctx, RankService_GetTopN_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankServiceServer is the server API for RankService service.
// All implementations must embed UnimplementedRankServiceServer
// for forward compatibility
type RankServiceServer interface {
	// 提交一场战斗的分数
	SubmitScore(context.Context, *ScoreReq) (*ScoreRsp, error)
	// 获取 TopN 排行
	GetTopN(context.Context, *TopNReq) (*TopNRsp, error)
	mustEmbedUnimplementedRankServiceServer()
}

// UnimplementedRankServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRankServiceServer struct {
}

func (UnimplementedRankServiceServer) SubmitScore(context.Context, *ScoreReq) (*ScoreRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitScore not implemented")
}
func (UnimplementedRankServiceServer) GetTopN(context.Context, *TopNReq) (*TopNRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopN not implemented")
}
func (UnimplementedRankServiceServer) mustEmbedUnimplementedRankServiceServer() {}

// UnsafeRankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankServiceServer will
// result in compilation errors.
type UnsafeRankServiceServer interface {
	mustEmbedUnimplementedRankServiceServer()
}

func RegisterRankServiceServer(s grpc.ServiceRegistrar, srv RankServiceServer) {
	s.RegisterService(&RankService_ServiceDesc, srv)
}

func _RankService_SubmitScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).SubmitScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankService_SubmitScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).SubmitScore(ctx, req.(*ScoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankService_GetTopN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopNReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).GetTopN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankService_GetTopN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).GetTopN(ctx, req.(*TopNReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RankService_ServiceDesc is the grpc.ServiceDesc for RankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gs.cluster.RankService",
	HandlerType: (*RankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitScore",
			Handler:    _RankService_SubmitScore_Handler,
		},
		{
			MethodName: "GetTopN",
			Handler:    _RankService_GetTopN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}
