// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: cluster.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	mi := &file_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *AuthReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AuthReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Player        *PlayerBase            `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRsp) Reset() {
	*x = AuthRsp{}
	mi := &file_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRsp) ProtoMessage() {}

func (x *AuthRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRsp.ProtoReflect.Descriptor instead.
func (*AuthRsp) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthRsp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuthRsp) GetPlayer() *PlayerBase {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *AuthRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 与 gs.protocol.RegisterReq 同名字段（避免与客户端协议消息在 pb 包内重名）
type RegisterAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // 可选昵称，留空默认用账号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccountReq) Reset() {
	*x = RegisterAccountReq{}
	mi := &file_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountReq) ProtoMessage() {}

func (x *RegisterAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountReq.ProtoReflect.Descriptor instead.
func (*RegisterAccountReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAccountReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterAccountReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterAccountReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterAccountRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Player        *PlayerBase            `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"` // 注册成功后直接签发，客户端可自动登录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccountRsp) Reset() {
	*x = RegisterAccountRsp{}
	mi := &file_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountRsp) ProtoMessage() {}

func (x *RegisterAccountRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountRsp.ProtoReflect.Descriptor instead.
func (*RegisterAccountRsp) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAccountRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterAccountRsp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RegisterAccountRsp) GetPlayer() *PlayerBase {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *RegisterAccountRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenReq) Reset() {
	*x = TokenReq{}
	mi := &file_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenReq) ProtoMessage() {}

func (x *TokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenReq.ProtoReflect.Descriptor instead.
func (*TokenReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *TokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Player        *PlayerBase            `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRsp) Reset() {
	*x = TokenRsp{}
	mi := &file_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRsp) ProtoMessage() {}

func (x *TokenRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRsp.ProtoReflect.Descriptor instead.
func (*TokenRsp) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *TokenRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TokenRsp) GetPlayer() *PlayerBase {
	if x != nil {
		return x.Player
	}
	return nil
}

type RegReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 实例名，如 game-1
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"` // login/gateway/game/rank/center
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegReq) Reset() {
	*x = RegReq{}
	mi := &file_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegReq) ProtoMessage() {}

func (x *RegReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegReq.ProtoReflect.Descriptor instead.
func (*RegReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *RegReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegReq) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegReq) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegReq) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type RegRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegRsp) Reset() {
	*x = RegRsp{}
	mi := &file_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegRsp) ProtoMessage() {}

func (x *RegRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegRsp.ProtoReflect.Descriptor instead.
func (*RegRsp) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *RegRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegRsp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{8}
}

type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ServiceEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEntry) Reset() {
	*x = ServiceEntry{}
	mi := &file_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEntry) ProtoMessage() {}

func (x *ServiceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEntry.ProtoReflect.Descriptor instead.
func (*ServiceEntry) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceEntry) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceEntry) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServiceEntry) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceEntry) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ServiceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceEntry        `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList) Reset() {
	*x = ServiceList{}
	mi := &file_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList) ProtoMessage() {}

func (x *ServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList.ProtoReflect.Descriptor instead.
func (*ServiceList) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceList) GetServices() []*ServiceEntry {
	if x != nil {
		return x.Services
	}
	return nil
}

type CreateBattleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Players       []*PlayerBase          `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Mode          int32                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"` // 0=帧同步 1=状态同步
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBattleReq) Reset() {
	*x = CreateBattleReq{}
	mi := &file_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBattleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBattleReq) ProtoMessage() {}

func (x *CreateBattleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBattleReq.ProtoReflect.Descriptor instead.
func (*CreateBattleReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *CreateBattleReq) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *CreateBattleReq) GetPlayers() []*PlayerBase {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *CreateBattleReq) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type CreateBattleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBattleRsp) Reset() {
	*x = CreateBattleRsp{}
	mi := &file_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBattleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBattleRsp) ProtoMessage() {}

func (x *CreateBattleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBattleRsp.ProtoReflect.Descriptor instead.
func (*CreateBattleRsp) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *CreateBattleRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateBattleRsp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SubmitOpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Seq           int32                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	OpData        string                 `protobuf:"bytes,4,opt,name=op_data,json=opData,proto3" json:"op_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOpReq) Reset() {
	*x = SubmitOpReq{}
	mi := &file_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOpReq) ProtoMessage() {}

func (x *SubmitOpReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOpReq.ProtoReflect.Descriptor instead.
func (*SubmitOpReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitOpReq) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *SubmitOpReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *SubmitOpReq) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SubmitOpReq) GetOpData() string {
	if x != nil {
		return x.OpData
	}
	return ""
}

type SubmitOpRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	AcceptedFrame int32                  `protobuf:"varint,3,opt,name=accepted_frame,json=acceptedFrame,proto3" json:"accepted_frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOpRsp) Reset() {
	*x = SubmitOpRsp{}
	mi := &file_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOpRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOpRsp) ProtoMessage() {}

func (x *SubmitOpRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOpRsp.ProtoReflect.Descriptor instead.
func (*SubmitOpRsp) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *SubmitOpRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SubmitOpRsp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SubmitOpRsp) GetAcceptedFrame() int32 {
	if x != nil {
		return x.AcceptedFrame
	}
	return 0
}

type FinishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	WinnerId      int64                  `protobuf:"varint,2,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	WinnerScore   int32                  `protobuf:"varint,3,opt,name=winner_score,json=winnerScore,proto3" json:"winner_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishReq) Reset() {
	*x = FinishReq{}
	mi := &file_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishReq) ProtoMessage() {}

func (x *FinishReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishReq.ProtoReflect.Descriptor instead.
func (*FinishReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *FinishReq) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *FinishReq) GetWinnerId() int64 {
	if x != nil {
		return x.WinnerId
	}
	return 0
}

func (x *FinishReq) GetWinnerScore() int32 {
	if x != nil {
		return x.WinnerScore
	}
	return 0
}

type MatchJoinReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PlayerId   int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	// 玩家所在网关地址（host:grpc_port），游戏服据此推送快照
	GatewayAddr string `protobuf:"bytes,3,opt,name=gateway_addr,json=gatewayAddr,proto3" json:"gateway_addr,omitempty"`
	// 对局模式：0=帧同步 1=状态同步（默认状态同步）
	Mode          int32 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchJoinReq) Reset() {
	*x = MatchJoinReq{}
	mi := &file_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchJoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchJoinReq) ProtoMessage() {}

func (x *MatchJoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchJoinReq.ProtoReflect.Descriptor instead.
func (*MatchJoinReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{17}
}

func (x *MatchJoinReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MatchJoinReq) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *MatchJoinReq) GetGatewayAddr() string {
	if x != nil {
		return x.GatewayAddr
	}
	return ""
}

func (x *MatchJoinReq) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type MatchJoinRsp struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Ok     bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// 0 表示已入队排队中（配对结果需 QueryMatchResult 轮询）
	RoomId        int64 `protobuf:"varint,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchJoinRsp) Reset() {
	*x = MatchJoinRsp{}
	mi := &file_cluster_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchJoinRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchJoinRsp) ProtoMessage() {}

func (x *MatchJoinRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchJoinRsp.ProtoReflect.Descriptor instead.
func (*MatchJoinRsp) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{18}
}

func (x *MatchJoinRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MatchJoinRsp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MatchJoinRsp) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type MatchQueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchQueryReq) Reset() {
	*x = MatchQueryReq{}
	mi := &file_cluster_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchQueryReq) ProtoMessage() {}

func (x *MatchQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchQueryReq.ProtoReflect.Descriptor instead.
func (*MatchQueryReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{19}
}

func (x *MatchQueryReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type MatchQueryRsp struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Ok     bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// 0 表示仍在排队
	RoomId        int64 `protobuf:"varint,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchQueryRsp) Reset() {
	*x = MatchQueryRsp{}
	mi := &file_cluster_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchQueryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchQueryRsp) ProtoMessage() {}

func (x *MatchQueryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchQueryRsp.ProtoReflect.Descriptor instead.
func (*MatchQueryRsp) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{20}
}

func (x *MatchQueryRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MatchQueryRsp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MatchQueryRsp) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type OpForwardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Op            *OpInput               `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpForwardReq) Reset() {
	*x = OpForwardReq{}
	mi := &file_cluster_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpForwardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpForwardReq) ProtoMessage() {}

func (x *OpForwardReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpForwardReq.ProtoReflect.Descriptor instead.
func (*OpForwardReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{21}
}

func (x *OpForwardReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *OpForwardReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *OpForwardReq) GetOp() *OpInput {
	if x != nil {
		return x.Op
	}
	return nil
}

type OpForwardRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpForwardRsp) Reset() {
	*x = OpForwardRsp{}
	mi := &file_cluster_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpForwardRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpForwardRsp) ProtoMessage() {}

func (x *OpForwardRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpForwardRsp.ProtoReflect.Descriptor instead.
func (*OpForwardRsp) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{22}
}

func (x *OpForwardRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OpForwardRsp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type QuitRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitRoomReq) Reset() {
	*x = QuitRoomReq{}
	mi := &file_cluster_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitRoomReq) ProtoMessage() {}

func (x *QuitRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitRoomReq.ProtoReflect.Descriptor instead.
func (*QuitRoomReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{23}
}

func (x *QuitRoomReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *QuitRoomReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 玩家在匹配等待中下线（网关断连检测后广播，从匹配池移除）
type LeaveMatchReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PlayerId   int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	// 玩家所在网关地址（与 JoinMatch 的 gateway_addr 同源，用于构造池 member）
	GatewayAddr   string `protobuf:"bytes,3,opt,name=gateway_addr,json=gatewayAddr,proto3" json:"gateway_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveMatchReq) Reset() {
	*x = LeaveMatchReq{}
	mi := &file_cluster_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveMatchReq) ProtoMessage() {}

func (x *LeaveMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveMatchReq.ProtoReflect.Descriptor instead.
func (*LeaveMatchReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{24}
}

func (x *LeaveMatchReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *LeaveMatchReq) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *LeaveMatchReq) GetGatewayAddr() string {
	if x != nil {
		return x.GatewayAddr
	}
	return ""
}

type SnapshotPushReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Snapshot      *StateSnapshot         `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotPushReq) Reset() {
	*x = SnapshotPushReq{}
	mi := &file_cluster_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotPushReq) ProtoMessage() {}

func (x *SnapshotPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotPushReq.ProtoReflect.Descriptor instead.
func (*SnapshotPushReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{25}
}

func (x *SnapshotPushReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *SnapshotPushReq) GetSnapshot() *StateSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type FramePushReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Frame         *FrameData             `protobuf:"bytes,2,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FramePushReq) Reset() {
	*x = FramePushReq{}
	mi := &file_cluster_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FramePushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FramePushReq) ProtoMessage() {}

func (x *FramePushReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FramePushReq.ProtoReflect.Descriptor instead.
func (*FramePushReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{26}
}

func (x *FramePushReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *FramePushReq) GetFrame() *FrameData {
	if x != nil {
		return x.Frame
	}
	return nil
}

type ResultPushReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 目标玩家
	Result        *BattleResult          `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultPushReq) Reset() {
	*x = ResultPushReq{}
	mi := &file_cluster_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultPushReq) ProtoMessage() {}

func (x *ResultPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultPushReq.ProtoReflect.Descriptor instead.
func (*ResultPushReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{27}
}

func (x *ResultPushReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ResultPushReq) GetResult() *BattleResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ScoreReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreReq) Reset() {
	*x = ScoreReq{}
	mi := &file_cluster_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreReq) ProtoMessage() {}

func (x *ScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreReq.ProtoReflect.Descriptor instead.
func (*ScoreReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{28}
}

func (x *ScoreReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ScoreReq) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ScoreRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"` // 提交后玩家当前名次
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRsp) Reset() {
	*x = ScoreRsp{}
	mi := &file_cluster_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRsp) ProtoMessage() {}

func (x *ScoreRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRsp.ProtoReflect.Descriptor instead.
func (*ScoreRsp) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{29}
}

func (x *ScoreRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ScoreRsp) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type TopNReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopNReq) Reset() {
	*x = TopNReq{}
	mi := &file_cluster_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopNReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNReq) ProtoMessage() {}

func (x *TopNReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopNReq.ProtoReflect.Descriptor instead.
func (*TopNReq) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{30}
}

func (x *TopNReq) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type TopNRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerBase          `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopNRsp) Reset() {
	*x = TopNRsp{}
	mi := &file_cluster_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopNRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNRsp) ProtoMessage() {}

func (x *TopNRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopNRsp.ProtoReflect.Descriptor instead.
func (*TopNRsp) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{31}
}

func (x *TopNRsp) GetPlayers() []*PlayerBase {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_cluster_proto protoreflect.FileDescriptor

const file_cluster_proto_rawDesc = "" +
	"\n" +
	"\rcluster.proto\x12\n" +
	"gs.cluster\x1a\fcommon.proto\x1a\x0eprotocol.proto\"?\n" +
	"\aAuthReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"v\n" +
	"\aAuthRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12-\n" +
	"\x06player\x18\x03 \x01(\v2\x15.gs.common.PlayerBaseR\x06player\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"^\n" +
	"\x12RegisterAccountReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x81\x01\n" +
	"\x12RegisterAccountRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12-\n" +
	"\x06player\x18\x03 \x01(\v2\x15.gs.common.PlayerBaseR\x06player\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\" \n" +
	"\bTokenReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"I\n" +
	"\bTokenRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12-\n" +
	"\x06player\x18\x02 \x01(\v2\x15.gs.common.PlayerBaseR\x06player\"g\n" +
	"\x06RegReq\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\"0\n" +
	"\x06RegRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\a\n" +
	"\x05Empty\"1\n" +
	"\fHeartbeatReq\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"m\n" +
	"\fServiceEntry\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\"C\n" +
	"\vServiceList\x124\n" +
	"\bservices\x18\x01 \x03(\v2\x18.gs.cluster.ServiceEntryR\bservices\"s\n" +
	"\x0fCreateBattleReq\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x12/\n" +
	"\aplayers\x18\x02 \x03(\v2\x15.gs.common.PlayerBaseR\aplayers\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\x05R\x04mode\"9\n" +
	"\x0fCreateBattleRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"r\n" +
	"\vSubmitOpReq\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x05R\x03seq\x12\x17\n" +
	"\aop_data\x18\x04 \x01(\tR\x06opData\"\\\n" +
	"\vSubmitOpRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0eaccepted_frame\x18\x03 \x01(\x05R\racceptedFrame\"h\n" +
	"\tFinishReq\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x12\x1b\n" +
	"\twinner_id\x18\x02 \x01(\x03R\bwinnerId\x12!\n" +
	"\fwinner_score\x18\x03 \x01(\x05R\vwinnerScore\"\x83\x01\n" +
	"\fMatchJoinReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12!\n" +
	"\fgateway_addr\x18\x03 \x01(\tR\vgatewayAddr\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\x05R\x04mode\"O\n" +
	"\fMatchJoinRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\x03R\x06roomId\",\n" +
	"\rMatchQueryReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"P\n" +
	"\rMatchQueryRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\x03R\x06roomId\"j\n" +
	"\fOpForwardReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12$\n" +
	"\x02op\x18\x03 \x01(\v2\x14.gs.protocol.OpInputR\x02op\"6\n" +
	"\fOpForwardRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"C\n" +
	"\vQuitRoomReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\"p\n" +
	"\rLeaveMatchReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12!\n" +
	"\fgateway_addr\x18\x03 \x01(\tR\vgatewayAddr\"f\n" +
	"\x0fSnapshotPushReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x126\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x1a.gs.protocol.StateSnapshotR\bsnapshot\"Y\n" +
	"\fFramePushReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12,\n" +
	"\x05frame\x18\x02 \x01(\v2\x16.gs.protocol.FrameDataR\x05frame\"_\n" +
	"\rResultPushReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x121\n" +
	"\x06result\x18\x02 \x01(\v2\x19.gs.protocol.BattleResultR\x06result\"=\n" +
	"\bScoreReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\".\n" +
	"\bScoreRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\"\x17\n" +
	"\aTopNReq\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\":\n" +
	"\aTopNRsp\x12/\n" +
	"\aplayers\x18\x01 \x03(\v2\x15.gs.common.PlayerBaseR\aplayers2\x94\x01\n" +
	"\fLoginService\x128\n" +
	"\fAuthenticate\x12\x13.gs.cluster.AuthReq\x1a\x13.gs.cluster.AuthRsp\x12J\n" +
	"\bRegister\x12\x1e.gs.cluster.RegisterAccountReq\x1a\x1e.gs.cluster.RegisterAccountRsp2\xfd\x01\n" +
	"\rCenterService\x129\n" +
	"\vVerifyToken\x12\x14.gs.cluster.TokenReq\x1a\x14.gs.cluster.TokenRsp\x129\n" +
	"\x0fRegisterService\x12\x12.gs.cluster.RegReq\x1a\x12.gs.cluster.RegRsp\x12<\n" +
	"\x0eGetServiceList\x12\x11.gs.cluster.Empty\x1a\x17.gs.cluster.ServiceList\x128\n" +
	"\tHeartbeat\x12\x18.gs.cluster.HeartbeatReq\x1a\x11.gs.cluster.Empty2\xd1\x01\n" +
	"\rBattleService\x12H\n" +
	"\fCreateBattle\x12\x1b.gs.cluster.CreateBattleReq\x1a\x1b.gs.cluster.CreateBattleRsp\x12<\n" +
	"\bSubmitOp\x12\x17.gs.cluster.SubmitOpReq\x1a\x17.gs.cluster.SubmitOpRsp\x128\n" +
	"\fFinishBattle\x12\x15.gs.cluster.FinishReq\x1a\x11.gs.cluster.Empty2\xcc\x02\n" +
	"\vGameService\x12?\n" +
	"\tJoinMatch\x12\x18.gs.cluster.MatchJoinReq\x1a\x18.gs.cluster.MatchJoinRsp\x12H\n" +
	"\x10QueryMatchResult\x12\x19.gs.cluster.MatchQueryReq\x1a\x19.gs.cluster.MatchQueryRsp\x12>\n" +
	"\bSubmitOp\x12\x18.gs.cluster.OpForwardReq\x1a\x18.gs.cluster.OpForwardRsp\x126\n" +
	"\bQuitRoom\x12\x17.gs.cluster.QuitRoomReq\x1a\x11.gs.cluster.Empty\x12:\n" +
	"\n" +
	"LeaveMatch\x12\x19.gs.cluster.LeaveMatchReq\x1a\x11.gs.cluster.Empty2\xca\x01\n" +
	"\x12GatewayPushService\x12>\n" +
	"\fPushSnapshot\x12\x1b.gs.cluster.SnapshotPushReq\x1a\x11.gs.cluster.Empty\x128\n" +
	"\tPushFrame\x12\x18.gs.cluster.FramePushReq\x1a\x11.gs.cluster.Empty\x12:\n" +
	"\n" +
	"PushResult\x12\x19.gs.cluster.ResultPushReq\x1a\x11.gs.cluster.Empty2}\n" +
	"\vRankService\x129\n" +
	"\vSubmitScore\x12\x14.gs.cluster.ScoreReq\x1a\x14.gs.cluster.ScoreRsp\x123\n" +
	"\aGetTopN\x12\x13.gs.cluster.TopNReq\x1a\x13.gs.cluster.TopNRspB\x16Z\x14gameserver/api/pb;pbb\x06proto3"

var (
	file_cluster_proto_rawDescOnce sync.Once
	file_cluster_proto_rawDescData []byte
)

func file_cluster_proto_rawDescGZIP() []byte {
	file_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)))
	})
	return file_cluster_proto_rawDescData
}

var file_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_cluster_proto_goTypes = []any{
	(*AuthReq)(nil),            // 0: gs.cluster.AuthReq
	(*AuthRsp)(nil),            // 1: gs.cluster.AuthRsp
	(*RegisterAccountReq)(nil), // 2: gs.cluster.RegisterAccountReq
	(*RegisterAccountRsp)(nil), // 3: gs.cluster.RegisterAccountRsp
	(*TokenReq)(nil),           // 4: gs.cluster.TokenReq
	(*TokenRsp)(nil),           // 5: gs.cluster.TokenRsp
	(*RegReq)(nil),             // 6: gs.cluster.RegReq
	(*RegRsp)(nil),             // 7: gs.cluster.RegRsp
	(*Empty)(nil),              // 8: gs.cluster.Empty
	(*HeartbeatReq)(nil),       // 9: gs.cluster.HeartbeatReq
	(*ServiceEntry)(nil),       // 10: gs.cluster.ServiceEntry
	(*ServiceList)(nil),        // 11: gs.cluster.ServiceList
	(*CreateBattleReq)(nil),    // 12: gs.cluster.CreateBattleReq
	(*CreateBattleRsp)(nil),    // 13: gs.cluster.CreateBattleRsp
	(*SubmitOpReq)(nil),        // 14: gs.cluster.SubmitOpReq
	(*SubmitOpRsp)(nil),        // 15: gs.cluster.SubmitOpRsp
	(*FinishReq)(nil),          // 16: gs.cluster.FinishReq
	(*MatchJoinReq)(nil),       // 17: gs.cluster.MatchJoinReq
	(*MatchJoinRsp)(nil),       // 18: gs.cluster.MatchJoinRsp
	(*MatchQueryReq)(nil),      // 19: gs.cluster.MatchQueryReq
	(*MatchQueryRsp)(nil),      // 20: gs.cluster.MatchQueryRsp
	(*OpForwardReq)(nil),       // 21: gs.cluster.OpForwardReq
	(*OpForwardRsp)(nil),       // 22: gs.cluster.OpForwardRsp
	(*QuitRoomReq)(nil),        // 23: gs.cluster.QuitRoomReq
	(*LeaveMatchReq)(nil),      // 24: gs.cluster.LeaveMatchReq
	(*SnapshotPushReq)(nil),    // 25: gs.cluster.SnapshotPushReq
	(*FramePushReq)(nil),       // 26: gs.cluster.FramePushReq
	(*ResultPushReq)(nil),      // 27: gs.cluster.ResultPushReq
	(*ScoreReq)(nil),           // 28: gs.cluster.ScoreReq
	(*ScoreRsp)(nil),           // 29: gs.cluster.ScoreRsp
	(*TopNReq)(nil),            // 30: gs.cluster.TopNReq
	(*TopNRsp)(nil),            // 31: gs.cluster.TopNRsp
	(*PlayerBase)(nil),         // 32: gs.common.PlayerBase
	(*OpInput)(nil),            // 33: gs.protocol.OpInput
	(*StateSnapshot)(nil),      // 34: gs.protocol.StateSnapshot
	(*FrameData)(nil),          // 35: gs.protocol.FrameData
	(*BattleResult)(nil),       // 36: gs.protocol.BattleResult
}
var file_cluster_proto_depIdxs = []int32{
	32, // 0: gs.cluster.AuthRsp.player:type_name -> gs.common.PlayerBase
	32, // 1: gs.cluster.RegisterAccountRsp.player:type_name -> gs.common.PlayerBase
	32, // 2: gs.cluster.TokenRsp.player:type_name -> gs.common.PlayerBase
	10, // 3: gs.cluster.ServiceList.services:type_name -> gs.cluster.ServiceEntry
	32, // 4: gs.cluster.CreateBattleReq.players:type_name -> gs.common.PlayerBase
	33, // 5: gs.cluster.OpForwardReq.op:type_name -> gs.protocol.OpInput
	34, // 6: gs.cluster.SnapshotPushReq.snapshot:type_name -> gs.protocol.StateSnapshot
	35, // 7: gs.cluster.FramePushReq.frame:type_name -> gs.protocol.FrameData
	36, // 8: gs.cluster.ResultPushReq.result:type_name -> gs.protocol.BattleResult
	32, // 9: gs.cluster.TopNRsp.players:type_name -> gs.common.PlayerBase
	0,  // 10: gs.cluster.LoginService.Authenticate:input_type -> gs.cluster.AuthReq
	2,  // 11: gs.cluster.LoginService.Register:input_type -> gs.cluster.RegisterAccountReq
	4,  // 12: gs.cluster.CenterService.VerifyToken:input_type -> gs.cluster.TokenReq
	6,  // 13: gs.cluster.CenterService.RegisterService:input_type -> gs.cluster.RegReq
	8,  // 14: gs.cluster.CenterService.GetServiceList:input_type -> gs.cluster.Empty
	9,  // 15: gs.cluster.CenterService.Heartbeat:input_type -> gs.cluster.HeartbeatReq
	12, // 16: gs.cluster.BattleService.CreateBattle:input_type -> gs.cluster.CreateBattleReq
	14, // 17: gs.cluster.BattleService.SubmitOp:input_type -> gs.cluster.SubmitOpReq
	16, // 18: gs.cluster.BattleService.FinishBattle:input_type -> gs.cluster.FinishReq
	17, // 19: gs.cluster.GameService.JoinMatch:input_type -> gs.cluster.MatchJoinReq
	19, // 20: gs.cluster.GameService.QueryMatchResult:input_type -> gs.cluster.MatchQueryReq
	21, // 21: gs.cluster.GameService.SubmitOp:input_type -> gs.cluster.OpForwardReq
	23, // 22: gs.cluster.GameService.QuitRoom:input_type -> gs.cluster.QuitRoomReq
	24, // 23: gs.cluster.GameService.LeaveMatch:input_type -> gs.cluster.LeaveMatchReq
	25, // 24: gs.cluster.GatewayPushService.PushSnapshot:input_type -> gs.cluster.SnapshotPushReq
	26, // 25: gs.cluster.GatewayPushService.PushFrame:input_type -> gs.cluster.FramePushReq
	27, // 26: gs.cluster.GatewayPushService.PushResult:input_type -> gs.cluster.ResultPushReq
	28, // 27: gs.cluster.RankService.SubmitScore:input_type -> gs.cluster.ScoreReq
	30, // 28: gs.cluster.RankService.GetTopN:input_type -> gs.cluster.TopNReq
	1,  // 29: gs.cluster.LoginService.Authenticate:output_type -> gs.cluster.AuthRsp
	3,  // 30: gs.cluster.LoginService.Register:output_type -> gs.cluster.RegisterAccountRsp
	5,  // 31: gs.cluster.CenterService.VerifyToken:output_type -> gs.cluster.TokenRsp
	7,  // 32: gs.cluster.CenterService.RegisterService:output_type -> gs.cluster.RegRsp
	11, // 33: gs.cluster.CenterService.GetServiceList:output_type -> gs.cluster.ServiceList
	8,  // 34: gs.cluster.CenterService.Heartbeat:output_type -> gs.cluster.Empty
	13, // 35: gs.cluster.BattleService.CreateBattle:output_type -> gs.cluster.CreateBattleRsp
	15, // 36: gs.cluster.BattleService.SubmitOp:output_type -> gs.cluster.SubmitOpRsp
	8,  // 37: gs.cluster.BattleService.FinishBattle:output_type -> gs.cluster.Empty
	18, // 38: gs.cluster.GameService.JoinMatch:output_type -> gs.cluster.MatchJoinRsp
	20, // 39: gs.cluster.GameService.QueryMatchResult:output_type -> gs.cluster.MatchQueryRsp
	22, // 40: gs.cluster.GameService.SubmitOp:output_type -> gs.cluster.OpForwardRsp
	8,  // 41: gs.cluster.GameService.QuitRoom:output_type -> gs.cluster.Empty
	8,  // 42: gs.cluster.GameService.LeaveMatch:output_type -> gs.cluster.Empty
	8,  // 43: gs.cluster.GatewayPushService.PushSnapshot:output_type -> gs.cluster.Empty
	8,  // 44: gs.cluster.GatewayPushService.PushFrame:output_type -> gs.cluster.Empty
	8,  // 45: gs.cluster.GatewayPushService.PushResult:output_type -> gs.cluster.Empty
	29, // 46: gs.cluster.RankService.SubmitScore:output_type -> gs.cluster.ScoreRsp
	31, // 47: gs.cluster.RankService.GetTopN:output_type -> gs.cluster.TopNRsp
	29, // [29:48] is the sub-list for method output_type
	10, // [10:29] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cluster_proto_init() }
func file_cluster_proto_init() {
	if File_cluster_proto != nil {
		return
	}
	file_common_proto_init()
	file_protocol_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_proto_depIdxs,
		MessageInfos:      file_cluster_proto_msgTypes,
	}.Build()
	File_cluster_proto = out.File
	file_cluster_proto_goTypes = nil
	file_cluster_proto_depIdxs = nil
}
