// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: protocol.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---- 3. 玩家操作----
type OpType int32

const (
	OpType_OP_NONE  OpType = 0
	OpType_OP_MOVE  OpType = 1 // 移动
	OpType_OP_ATK   OpType = 2 // 普攻
	OpType_OP_SKILL OpType = 3 // 技能
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "OP_NONE",
		1: "OP_MOVE",
		2: "OP_ATK",
		3: "OP_SKILL",
	}
	OpType_value = map[string]int32{
		"OP_NONE":  0,
		"OP_MOVE":  1,
		"OP_ATK":   2,
		"OP_SKILL": 3,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

type BattleEvent_Type int32

const (
	BattleEvent_EV_NONE  BattleEvent_Type = 0
	BattleEvent_EV_ATK   BattleEvent_Type = 1 // 普攻命中
	BattleEvent_EV_SKILL BattleEvent_Type = 2 // 技能命中
	BattleEvent_EV_DEAD  BattleEvent_Type = 3 // 玩家阵亡
)

// Enum value maps for BattleEvent_Type.
var (
	BattleEvent_Type_name = map[int32]string{
		0: "EV_NONE",
		1: "EV_ATK",
		2: "EV_SKILL",
		3: "EV_DEAD",
	}
	BattleEvent_Type_value = map[string]int32{
		"EV_NONE":  0,
		"EV_ATK":   1,
		"EV_SKILL": 2,
		"EV_DEAD":  3,
	}
)

func (x BattleEvent_Type) Enum() *BattleEvent_Type {
	p := new(BattleEvent_Type)
	*p = x
	return p
}

func (x BattleEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[1].Descriptor()
}

func (BattleEvent_Type) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[1]
}

func (x BattleEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleEvent_Type.Descriptor instead.
func (BattleEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{8, 0}
}

// ---- 1. 登录 ----
type LoginReq struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Account  string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 断线重连时复用 token，携带则跳过密码校验
	Token         string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Player        *PlayerBase            `protobuf:"bytes,4,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRsp) Reset() {
	*x = LoginRsp{}
	mi := &file_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRsp) ProtoMessage() {}

func (x *LoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRsp.ProtoReflect.Descriptor instead.
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LoginRsp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LoginRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginRsp) GetPlayer() *PlayerBase {
	if x != nil {
		return x.Player
	}
	return nil
}

// ---- 1.1 注册----
type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // 可选昵称，留空默认用账号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // 注册成功后直接签发，客户端可自动登录
	Player        *PlayerBase            `protobuf:"bytes,4,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRsp) Reset() {
	*x = RegisterRsp{}
	mi := &file_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRsp) ProtoMessage() {}

func (x *RegisterRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRsp.ProtoReflect.Descriptor instead.
func (*RegisterRsp) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterRsp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RegisterRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRsp) GetPlayer() *PlayerBase {
	if x != nil {
		return x.Player
	}
	return nil
}

// ---- 2. 匹配 ----
type MatchReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Token string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// 对局模式：0=帧同步 1=状态同步
	Mode          int32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchReq) Reset() {
	*x = MatchReq{}
	mi := &file_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchReq) ProtoMessage() {}

func (x *MatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchReq.ProtoReflect.Descriptor instead.
func (*MatchReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *MatchReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MatchReq) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type MatchRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RoomId        int64                  `protobuf:"varint,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRsp) Reset() {
	*x = MatchRsp{}
	mi := &file_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRsp) ProtoMessage() {}

func (x *MatchRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRsp.ProtoReflect.Descriptor instead.
func (*MatchRsp) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *MatchRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MatchRsp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MatchRsp) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type OpInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int32                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // 客户端操作序号
	OpType        OpType                 `protobuf:"varint,2,opt,name=op_type,json=opType,proto3,enum=gs.protocol.OpType" json:"op_type,omitempty"`
	MoveDx        float32                `protobuf:"fixed32,3,opt,name=move_dx,json=moveDx,proto3" json:"move_dx,omitempty"` // OP_MOVE 方向
	MoveDy        float32                `protobuf:"fixed32,4,opt,name=move_dy,json=moveDy,proto3" json:"move_dy,omitempty"`
	TargetId      int64                  `protobuf:"varint,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // OP_ATK 目标
	SkillId       int32                  `protobuf:"varint,6,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`    // OP_SKILL 技能 id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpInput) Reset() {
	*x = OpInput{}
	mi := &file_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpInput) ProtoMessage() {}

func (x *OpInput) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpInput.ProtoReflect.Descriptor instead.
func (*OpInput) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *OpInput) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *OpInput) GetOpType() OpType {
	if x != nil {
		return x.OpType
	}
	return OpType_OP_NONE
}

func (x *OpInput) GetMoveDx() float32 {
	if x != nil {
		return x.MoveDx
	}
	return 0
}

func (x *OpInput) GetMoveDy() float32 {
	if x != nil {
		return x.MoveDy
	}
	return 0
}

func (x *OpInput) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *OpInput) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

// ---- 4. 状态同步快照 ----
type EntityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Hp            int32                  `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	Alive         bool                   `protobuf:"varint,5,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *EntityState) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *EntityState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *EntityState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *EntityState) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *EntityState) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type BattleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          BattleEvent_Type       `protobuf:"varint,1,opt,name=type,proto3,enum=gs.protocol.BattleEvent_Type" json:"type,omitempty"`
	AttackerId    int64                  `protobuf:"varint,2,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Damage        int32                  `protobuf:"varint,4,opt,name=damage,proto3" json:"damage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleEvent) Reset() {
	*x = BattleEvent{}
	mi := &file_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEvent) ProtoMessage() {}

func (x *BattleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEvent.ProtoReflect.Descriptor instead.
func (*BattleEvent) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *BattleEvent) GetType() BattleEvent_Type {
	if x != nil {
		return x.Type
	}
	return BattleEvent_EV_NONE
}

func (x *BattleEvent) GetAttackerId() int64 {
	if x != nil {
		return x.AttackerId
	}
	return 0
}

func (x *BattleEvent) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *BattleEvent) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type StateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Tick          int64                  `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`        // 逻辑帧号（20Hz）
	Entities      []*EntityState         `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"` // 全量实体状态（首帧）或增量
	Events        []*BattleEvent         `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`     // 本 tick 发生的战斗事件
	Full          bool                   `protobuf:"varint,5,opt,name=full,proto3" json:"full,omitempty"`        // true=全量快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *StateSnapshot) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *StateSnapshot) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *StateSnapshot) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *StateSnapshot) GetEvents() []*BattleEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *StateSnapshot) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

// ---- 4.1 帧同步输入帧----
type FrameOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Op            *OpInput               `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameOp) Reset() {
	*x = FrameOp{}
	mi := &file_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameOp) ProtoMessage() {}

func (x *FrameOp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameOp.ProtoReflect.Descriptor instead.
func (*FrameOp) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *FrameOp) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *FrameOp) GetOp() *OpInput {
	if x != nil {
		return x.Op
	}
	return nil
}

type FrameData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	FrameSeq      int64                  `protobuf:"varint,2,opt,name=frame_seq,json=frameSeq,proto3" json:"frame_seq,omitempty"` // 逻辑帧号
	Full          bool                   `protobuf:"varint,3,opt,name=full,proto3" json:"full,omitempty"`                         // 首帧 true：entities 携带出生点全量初始状态
	Entities      []*EntityState         `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities,omitempty"`                  // 仅 full=true 时有值
	Ops           []*FrameOp             `protobuf:"bytes,5,rep,name=ops,proto3" json:"ops,omitempty"`                            // 本帧各玩家操作（按 player_id 升序）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameData) Reset() {
	*x = FrameData{}
	mi := &file_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameData) ProtoMessage() {}

func (x *FrameData) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameData.ProtoReflect.Descriptor instead.
func (*FrameData) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *FrameData) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *FrameData) GetFrameSeq() int64 {
	if x != nil {
		return x.FrameSeq
	}
	return 0
}

func (x *FrameData) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *FrameData) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *FrameData) GetOps() []*FrameOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

// ---- 5. 对局结果 ----
type BattleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	WinnerId      int64                  `protobuf:"varint,2,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	LoserId       int64                  `protobuf:"varint,3,opt,name=loser_id,json=loserId,proto3" json:"loser_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // kill / timeout
	DurationS     int32                  `protobuf:"varint,5,opt,name=duration_s,json=durationS,proto3" json:"duration_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResult) Reset() {
	*x = BattleResult{}
	mi := &file_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResult) ProtoMessage() {}

func (x *BattleResult) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResult.ProtoReflect.Descriptor instead.
func (*BattleResult) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *BattleResult) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *BattleResult) GetWinnerId() int64 {
	if x != nil {
		return x.WinnerId
	}
	return 0
}

func (x *BattleResult) GetLoserId() int64 {
	if x != nil {
		return x.LoserId
	}
	return 0
}

func (x *BattleResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BattleResult) GetDurationS() int32 {
	if x != nil {
		return x.DurationS
	}
	return 0
}

// ---- 6. 排行榜 ----
type RankQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"` // TopN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankQuery) Reset() {
	*x = RankQuery{}
	mi := &file_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankQuery) ProtoMessage() {}

func (x *RankQuery) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankQuery.ProtoReflect.Descriptor instead.
func (*RankQuery) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *RankQuery) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type RankRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Players       []*PlayerBase          `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankRsp) Reset() {
	*x = RankRsp{}
	mi := &file_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankRsp) ProtoMessage() {}

func (x *RankRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankRsp.ProtoReflect.Descriptor instead.
func (*RankRsp) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *RankRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RankRsp) GetPlayers() []*PlayerBase {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_protocol_proto protoreflect.FileDescriptor

const file_protocol_proto_rawDesc = "" +
	"\n" +
	"\x0eprotocol.proto\x12\vgs.protocol\x1a\fcommon.proto\"V\n" +
	"\bLoginReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"w\n" +
	"\bLoginRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12-\n" +
	"\x06player\x18\x04 \x01(\v2\x15.gs.common.PlayerBaseR\x06player\"W\n" +
	"\vRegisterReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"z\n" +
	"\vRegisterRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12-\n" +
	"\x06player\x18\x04 \x01(\v2\x15.gs.common.PlayerBaseR\x06player\"4\n" +
	"\bMatchReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\x05R\x04mode\"K\n" +
	"\bMatchRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\x03R\x06roomId\"\xb3\x01\n" +
	"\aOpInput\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x05R\x03seq\x12,\n" +
	"\aop_type\x18\x02 \x01(\x0e2\x13.gs.protocol.OpTypeR\x06opType\x12\x17\n" +
	"\amove_dx\x18\x03 \x01(\x02R\x06moveDx\x12\x17\n" +
	"\amove_dy\x18\x04 \x01(\x02R\x06moveDy\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\x03R\btargetId\x12\x19\n" +
	"\bskill_id\x18\x06 \x01(\x05R\askillId\"l\n" +
	"\vEntityState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x0e\n" +
	"\x02hp\x18\x04 \x01(\x05R\x02hp\x12\x14\n" +
	"\x05alive\x18\x05 \x01(\bR\x05alive\"\xd2\x01\n" +
	"\vBattleEvent\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.gs.protocol.BattleEvent.TypeR\x04type\x12\x1f\n" +
	"\vattacker_id\x18\x02 \x01(\x03R\n" +
	"attackerId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06damage\x18\x04 \x01(\x05R\x06damage\":\n" +
	"\x04Type\x12\v\n" +
	"\aEV_NONE\x10\x00\x12\n" +
	"\n" +
	"\x06EV_ATK\x10\x01\x12\f\n" +
	"\bEV_SKILL\x10\x02\x12\v\n" +
	"\aEV_DEAD\x10\x03\"\xb8\x01\n" +
	"\rStateSnapshot\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x03R\x04tick\x124\n" +
	"\bentities\x18\x03 \x03(\v2\x18.gs.protocol.EntityStateR\bentities\x120\n" +
	"\x06events\x18\x04 \x03(\v2\x18.gs.protocol.BattleEventR\x06events\x12\x12\n" +
	"\x04full\x18\x05 \x01(\bR\x04full\"L\n" +
	"\aFrameOp\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12$\n" +
	"\x02op\x18\x02 \x01(\v2\x14.gs.protocol.OpInputR\x02op\"\xb3\x01\n" +
	"\tFrameData\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1b\n" +
	"\tframe_seq\x18\x02 \x01(\x03R\bframeSeq\x12\x12\n" +
	"\x04full\x18\x03 \x01(\bR\x04full\x124\n" +
	"\bentities\x18\x04 \x03(\v2\x18.gs.protocol.EntityStateR\bentities\x12&\n" +
	"\x03ops\x18\x05 \x03(\v2\x14.gs.protocol.FrameOpR\x03ops\"\x96\x01\n" +
	"\fBattleResult\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1b\n" +
	"\twinner_id\x18\x02 \x01(\x03R\bwinnerId\x12\x19\n" +
	"\bloser_id\x18\x03 \x01(\x03R\aloserId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"duration_s\x18\x05 \x01(\x05R\tdurationS\"\x19\n" +
	"\tRankQuery\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\"J\n" +
	"\aRankRsp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12/\n" +
	"\aplayers\x18\x02 \x03(\v2\x15.gs.common.PlayerBaseR\aplayers*<\n" +
	"\x06OpType\x12\v\n" +
	"\aOP_NONE\x10\x00\x12\v\n" +
	"\aOP_MOVE\x10\x01\x12\n" +
	"\n" +
	"\x06OP_ATK\x10\x02\x12\f\n" +
	"\bOP_SKILL\x10\x03B\x16Z\x14gameserver/api/pb;pbb\x06proto3"

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData []byte
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)))
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_protocol_proto_goTypes = []any{
	(OpType)(0),           // 0: gs.protocol.OpType
	(BattleEvent_Type)(0), // 1: gs.protocol.BattleEvent.Type
	(*LoginReq)(nil),      // 2: gs.protocol.LoginReq
	(*LoginRsp)(nil),      // 3: gs.protocol.LoginRsp
	(*RegisterReq)(nil),   // 4: gs.protocol.RegisterReq
	(*RegisterRsp)(nil),   // 5: gs.protocol.RegisterRsp
	(*MatchReq)(nil),      // 6: gs.protocol.MatchReq
	(*MatchRsp)(nil),      // 7: gs.protocol.MatchRsp
	(*OpInput)(nil),       // 8: gs.protocol.OpInput
	(*EntityState)(nil),   // 9: gs.protocol.EntityState
	(*BattleEvent)(nil),   // 10: gs.protocol.BattleEvent
	(*StateSnapshot)(nil), // 11: gs.protocol.StateSnapshot
	(*FrameOp)(nil),       // 12: gs.protocol.FrameOp
	(*FrameData)(nil),     // 13: gs.protocol.FrameData
	(*BattleResult)(nil),  // 14: gs.protocol.BattleResult
	(*RankQuery)(nil),     // 15: gs.protocol.RankQuery
	(*RankRsp)(nil),       // 16: gs.protocol.RankRsp
	(*PlayerBase)(nil),    // 17: gs.common.PlayerBase
}
var file_protocol_proto_depIdxs = []int32{
	17, // 0: gs.protocol.LoginRsp.player:type_name -> gs.common.PlayerBase
	17, // 1: gs.protocol.RegisterRsp.player:type_name -> gs.common.PlayerBase
	0,  // 2: gs.protocol.OpInput.op_type:type_name -> gs.protocol.OpType
	1,  // 3: gs.protocol.BattleEvent.type:type_name -> gs.protocol.BattleEvent.Type
	9,  // 4: gs.protocol.StateSnapshot.entities:type_name -> gs.protocol.EntityState
	10, // 5: gs.protocol.StateSnapshot.events:type_name -> gs.protocol.BattleEvent
	8,  // 6: gs.protocol.FrameOp.op:type_name -> gs.protocol.OpInput
	9,  // 7: gs.protocol.FrameData.entities:type_name -> gs.protocol.EntityState
	12, // 8: gs.protocol.FrameData.ops:type_name -> gs.protocol.FrameOp
	17, // 9: gs.protocol.RankRsp.players:type_name -> gs.common.PlayerBase
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		EnumInfos:         file_protocol_proto_enumTypes,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
